# Generated by Django 5.1.3 on 2025-03-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_customuser_is_superuser_customuser_user_permissions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
