# Generated by Django 5.1.5 on 2025-03-03 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("find_transport", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="battere_percentage",
            new_name="battery_percentage",
        ),
    ]
