# Generated by Django 5.1.3 on 2025-03-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("find_transport", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="battere_percentage",
            new_name="battery_percentage",
        ),
    ]
